func identity*(n: int): int =
  raise newException(ValueError, "myValueError")
